name: starbucksify
description: A silly package that converts a string to a Starbucks-like string.
version: 0.1.0+1
repository: https://github.cim/iamngoni/starbucksify

environment:
  sdk: "^3.3.0"

dev_dependencies:
  very_good_analysis: ">=5.1.0 <7.0.0"
